# Generated by Django 3.1 on 2022-10-21 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aseguramiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('responsable_email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name': 'Aseguramiento',
                'verbose_name_plural': 'Aseguramientos',
                'db_table': 'aseguramientos',
            },
        ),
    ]
