# Generated by Django 3.1 on 2022-10-21 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('area', '0001_initial'),
        ('medio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('capacidad', models.PositiveIntegerField()),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('responsable_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localarea', to='area.area')),
            ],
            options={
                'verbose_name': 'Local',
                'verbose_name_plural': 'Locales',
                'db_table': 'locales',
            },
        ),
        migrations.CreateModel(
            name='LocalMedio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medioslocales', to='local.local')),
                ('medio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medioslocales', to='medio.medio')),
            ],
            options={
                'verbose_name': 'LocalMedio',
                'verbose_name_plural': 'LocalMedios',
                'db_table': 'local_medio',
            },
        ),
        migrations.AddField(
            model_name='local',
            name='medios',
            field=models.ManyToManyField(through='local.LocalMedio', to='medio.Medio'),
        ),
    ]
