# Generated by Django 3.1 on 2022-10-21 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('local', '0001_initial'),
        ('aseguramiento', '0001_initial'),
        ('tipo_actividad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('cantidad_participantes', models.PositiveIntegerField()),
                ('responsable_email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'db_table': 'actividades',
            },
        ),
        migrations.CreateModel(
            name='Reservacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobada', 'Aprobada'), ('Cancelada', 'Cancelada')], default='Pendiente', max_length=50)),
                ('fecha_inico', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservaciones_actividad', to='actividad.actividad')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservaciones_local', to='local.local')),
            ],
            options={
                'verbose_name': 'Reservacion',
                'verbose_name_plural': 'Reservaciones',
                'db_table': 'reservacion',
            },
        ),
        migrations.CreateModel(
            name='ActividadAseguramiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividadaseguramientos', to='actividad.actividad')),
                ('aseguramiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividadaseguramientos', to='aseguramiento.aseguramiento')),
            ],
            options={
                'verbose_name': 'ActividadAseguramiento',
                'verbose_name_plural': 'ActividadAseguramientos',
                'db_table': 'actividad_aseguramiento',
            },
        ),
        migrations.AddField(
            model_name='actividad',
            name='aseguramientos',
            field=models.ManyToManyField(through='actividad.ActividadAseguramiento', to='aseguramiento.Aseguramiento'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='reservaciones',
            field=models.ManyToManyField(through='actividad.Reservacion', to='local.Local'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='tipo_actividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividad_tipoactividad', to='tipo_actividad.tipoactividad'),
        ),
    ]
